SELECT
  number,
  ordered_at_utc,
  shopify_transaction_id,
  email_hash,
  new_customer,
  returning_customer,
  customer_payment,
  total_discounts,
  IFNULL(tax_amount, 0) AS tax_amount,
  shipping_costs,
  subtotal,
  ROUND(SAFE_DIVIDE(total_discounts * 100, subtotal), 2) as discount_pct,
  tax_rate,
  tax_title,
  IFNULL(sum_refund_amount,0) AS sum_refund_amount,
  o.code,
  c.code_type AS code_channel,	
  currency,
  processing_method,
  gateway,
  shipping_method,
  shipping_country,
  tags,
  note,
  source_name,
  last_refund_at,
  financial_status,
  fulfillment_status,
  shopify_fulfilled_at,
  order_cancelled_at,
  order_updated_at,
  order_processed_at,
  order_closed_at,
  order_number,
  shop_order_reference,
  user_id,	
  customer_id,
  checkout_id,
  source 
FROM
  {{ ref('stg_orders_combined') }} O
LEFT JOIN {{ ref('stg_coupon_types') }} C ON C.code = O.code